### ISSUE TITLE
Selective GI dimming

### ISSUE THREAD

**Issue by robertvb83** [Stumblor/firmware-updates#2]
Hi there, i have an idea / feature request

In case you are idle and bored here's something to work on

I like GI sensing. But i dont like inserts to turn off when GI is off. This does not make sense to me, as all other inserts are usually still part of the light show.

So minimum brightness is great to deal with that, however i would like it better if minimum brightness could be attached to segments individually, e.g. i like everything on the building to turn OFF EXEPT for the actual insert lights.

E.g. i like the tokyo neon sign to turn off the right side illumination while i like the inserts to go to their minimum brightness setting (or full brightness)

By 'inserts', in the case of noodle/tokyo, i am referring to the signs indicators Battle/building/ etc.

Inserts are what indicate game functions. They are part of the light show even when GI is dim/off

Could you incorporate the option of which items to select during GI dimming?

Best regards
Robert / WizzardRob / Robotron

**Comment by Stumblor** [comment]
Great idea Rob, and now that you have mentioned it - seems so obvious. I'll get on it.

Loving my first firmware GitHub issue also! 🥳

**Comment by Stumblor** [comment]
Implemented in release v1.9.3

![image](https://github.com/Stumblor/firmware-updates/assets/3416626/87882b15-644d-4946-9655-93b8acc40177)

**Comment by robertvb83** [comment]
Oh wow you did it. Cool thanks!
I seem to not find 1.9.3 for tokyoneon and noodle. Is is online already to test?

**Comment by Stumblor** [comment]
I'll have to make that functionality backwards compatible for those two projects, since I wasn't using a single codebase at the time those were written. For the moment it's only those systems that derive from the core Lollypops code

                "Lollypops", 
                "LollyUFO", 
                "LollySpeakers", 
                "LollyGI", 
                "AtomicGodzilla", 
                "PhantomLanterns", 
                "Hellhouse",
                "Gappa",
                "Area51",
                "Subway"

I'll put it into TN and Noodle sometime over the next few days

**Comment by robertvb83** [comment]
Ah great, subway is on the way, cool cool

**Comment by Stumblor** [comment]
@robertvb83 added to NoodleBar firmware v1.0.4

**Comment by Stumblor** [comment]
@robertvb83 added to Tokyo Neon #1 v1.1.4

**Comment by robertvb83** [comment]
Thats awesome! I'll test and feedback that in a few days.

**Comment by Stumblor** [comment]
Since TN and Noodle use standalone (and older) versions of the firmware, the setting will just be on the main 'At Rest' LED screen, rather than under the gear tab.
